name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: Build CSS
        run: |
          npm ci
          npm run build:css

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.LINODEDEPLOY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -e -l -c "
            cd ~/ducksbucks &&
            git pull &&
            uv sync
          "'

      - name: Sync built CSS
        run: |
          rsync -av static/css/tailwind.min.css \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/ducksbucks/static/css/tailwind.min.css

      - name: Restart service
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'sudo systemctl restart ducksbucks'
